name: Build

on: push

jobs:
  build:
 #   if: "!contains(github.event.head_commit.message, 'ci-skip') && contains(github.event.head_commit.message, 'ci-build')"
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev libgtk-3-dev libwebkit2gtk-4.0-dev
      
      - name: Cargo Update
        uses: actions-rs/cargo@v1
        with:
          command: update
      
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release  --verbose
      
      - name: Upload Built Binary
        uses: actions/upload-artifact@v1
        with:
          name: soundsense-rs-${{runner.os}}
          path: target/release/soundsense-rs

      - name: Version
        if: startsWith(github.ref, 'refs/tags/')
        id: version_id
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: Package release
        if: startsWith(github.ref, 'refs/tags/')
        run: tar cjf soundsense-rs-linux-${{ steps.version_id.outputs.VERSION }}.tbz -C target/release/ soundsense-rs 


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            Build patched for linux only

          files: |
            soundsense-rs-linux-*.tbz

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
